### ISSUE TITLE
error trying to parse csv blob as json

### ISSUE THREAD

**Issue by saahiljaffer** [FlatFilers/flatfile-python#1]
hey all,

thanks for generating this library, unfortunately the client is trying to parse the download sheet response as json when it's actually a csv blob

https://github.com/FlatFilers/flatfile-python/blob/ea53846dc51ef17c6ef56f9476e193db40bb114f/src/flatfile/resources/sheets/client.py#L142

**Comment by ashleygmulligan2** [comment]
Thank you for catching this. This is now resolved in 0.0.4
