### ISSUE TITLE
ids field marked as required when it should be optional

### ISSUE THREAD

**Issue by saahiljaffer** [FlatFilers/flatfile-python#2]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1703090821632399)

https://github.com/FlatFilers/flatfile-python/blob/ee044b531bb23ac0dd2a35b76c8d88c027945acc/src/flatfile/resources/records/client.py#L54C1-L54C1

in the linked client (and in other places), it uses `ids: typing.Union[typing.Optional[RecordId], typing.List[RecordId]],` which should be optional (since you shouldn't have to pass an empty list of `ids`) but the types force you to pass something

**Comment by damonbanks** [comment]
Ticket filed: https://github.com/fern-api/fern/issues/2529

**Comment by damonbanks** [comment]
Just published a new version of our python SDK https://github.com/FlatFilers/Platform/releases/tag/%40flatfile%2Fpython%400.0.17

This should resolve this issue.

**Comment by damonbanks** [comment]
Reopening pending further investigation into upgrading packages.

**Comment by damonbanks** [comment]
We are blocked on upgrading the the version that is fixed by this bug in Fern: https://github.com/fern-api/fern/issues/2970 

They mentioned last week that they will be working on this.

**Comment by damonbanks** [comment]
The latest version of Fern fixed the blocker in order to upgrade our pythons SDK and fix this ticket. We have pushed the fern upgrade and a new version of our Python SDK.
